# Generated by Django 3.0.4 on 2020-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200316_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=40)),
                ('subscriber_email', models.EmailField(max_length=32)),
                ('subcriber_phone', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
