# Generated by Django 3.0.4 on 2020-04-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subcriber_phone',
            field=models.CharField(max_length=10),
        ),
    ]
