# Generated by Django 3.0.4 on 2020-04-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200401_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subcriber_phone',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
