# Generated by Django 3.0.4 on 2020-04-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_name', models.CharField(max_length=40)),
                ('therapist_email', models.EmailField(default='unspecified@foo.com', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=40)),
                ('patient_email', models.EmailField(default='unspecified@foo.com', max_length=40)),
                ('patient_phone_number', models.CharField(blank=True, max_length=10)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Therapist')),
            ],
        ),
    ]
