# Generated by Django 3.0.3 on 2020-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_email',
            field=models.EmailField(default='unspecified@foo.com', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='therapist',
            name='therapist_email',
            field=models.EmailField(default='unspecified@foo.com', max_length=40),
        ),
    ]
